import Head from "next/head"
import BackToTop from "../components/BackToTop/BackToTop"
import Header from "../components/Header/Header"
import Interests from "../sections/Interests/Interests"
import OthersWatching from "../sections/OthersWatching/OthersWatching"
import LatestCourse from "../sections/LatestCourse/LatestCourse"
import Tutorials from "../sections/Tutorials/Tutorials"
import SuitsBest from "../sections/SuitsBest/SuitsBest"
import Discover from "../sections/Discover/Discover"
import GetInspired from "../sections/GetInspired/GetInspired"
import Footer from "../sections/Footer/Footer"
import Logo from "../components/Logo/Logo"

import hamburger from "../public/ku-hamburger.png"
import search from "../public/ku-search.png"

import discover from "../public/ku-discover.png"
import library from "../public/ku-library.png"
import myuni from "../public/ku-myuni.png"

export default function Home() {
	return (
		<div>
			<Head>
				<title>Keysight University</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="layout">
				<div className="left-col">
					<nav className="navigation-bar">
						<div className="top-navigation-items">
							<Logo light />
							<button className="nav-item-button">
								<img src={hamburger} />
							</button>
							<button className="nav-item-button">
								<img src={search} />
							</button>
						</div>

						<div className="bottom-navigation-items">
							<button className="nav-item-button">
								<img src={discover} />
							</button>
							<button className="nav-item-button">
								<img src={library} />
							</button>
							<button className="nav-item-button">
								<img src={myuni} />
							</button>
						</div>
					</nav>
				</div>
				<div className="right-col">
					<main>
						<Header />
						<Interests />
						<BackToTop />
						<OthersWatching />
						<LatestCourse />
						<Tutorials />
						<SuitsBest />
						<Discover />
						<GetInspired />
					</main>
					<footer>
						<Footer />
					</footer>
				</div>
			</div>
		</div>
	)
}
