import Head from "next/head"
import Image from "next/image"
import BackToTop from "../components/BackToTop/BackToTop"
import Button from "../components/Button/Button"
import Header from "../components/Header/Header"
import Interests from "../components/Interests/Interests"
import Logo from "../components/Logo/Logo"

export default function Home() {
	return (
		<div>
			<Head>
				<title>Keysight University</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<Header />
				<Interests />
				<BackToTop />
			</main>
			<footer></footer>
		</div>
	)
}
